# github action 试用
name: star

on:
  watch: # 触发事件
    actions: started

jobs:
  deployment:
    runs-on: ubuntu-latest #镜像
    steps: #执行步骤
      - name: Star Count
        id: repo-stars
        uses: alanhg/repo-star-count-action@master
      - name: Notify
        run: |
          echo ${{github.event.sender.login}}
          echo ${{ steps.repo-stars.outputs.stars }}